#index:
#    path: /
#    controller: App\Controller\DefaultController::index
_translation_edit_in_place:
  resource: '@TranslationBundle/Resources/config/routing_edit_in_place.yml'
  prefix:  /admin
